# Project  

https://raw.githubusercontent.com/CunyLaguardiaDataAnalytics/datasets/master/2014-15_To_2016-17_School-_Level_NYC_Regents_Report_For_All_Variables.csv


set up your github account

set up a class projects repository (public, not private)

when you’re ready to submit your work, you’ll submit your github project link in google classroom

this will be the first project in your portfolio

you’ll add any future projects to your github to grow your portfolio for future employers and data endeavors you’ll want to pursue

there is a social network component to github as well, so you’ll want to think about ways to grow your network and grow your personal brand

https://github.com/cunylaguardiadataanalytics - our program

https://github.com/buildwelllabs - me

In [1]:
#Three libraries to bring at the onset

import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
matplotlib.style.use('ggplot')
%matplotlib inline

In [161]:
import seaborn as sns

In [162]:
import plotly.express as px

In [164]:
import plotly.graph_objects as go

In [218]:
# Importing the data

df = pd.read_csv('https://raw.githubusercontent.com/CunyLaguardiaDataAnalytics/datasets/master/2014-15_To_2016-17_School-_Level_NYC_Regents_Report_For_All_Variables.csv')

In [219]:
#Reviewing the columns

df.columns

Index(['School DBN', 'School Name', 'School Level', 'Regents Exam', 'Year',
       'Total Tested', 'Mean Score', 'Number Scoring Below 65',
       'Percent Scoring Below 65', 'Number Scoring 65 or Above',
       'Percent Scoring 65 or Above', 'Number Scoring 80 or Above',
       'Percent Scoring 80 or Above', 'Number Scoring CR',
       'Percent Scoring CR'],
      dtype='object')

In [220]:
# Reviewing the first five rows

df.head(5)

,School DBN,School Name,School Level,Regents Exam,Year,Total Tested,Mean Score,Number Scoring Below 65,Percent Scoring Below 65,Number Scoring 65 or Above,Percent Scoring 65 or Above,Number Scoring 80 or Above,Percent Scoring 80 or Above,Number Scoring CR,Percent Scoring CR
0,01M034,P.S. 034 Franklin D. Roosevelt,K-8,Common Core Algebra,2017,4,s,s,s,s,s,s,s,na,na
1,01M034,P.S. 034 Franklin D. Roosevelt,K-8,Living Environment,2015,16,77.9,1,6.3,15,93.8,7,43.8,na,na
2,01M034,P.S. 034 Franklin D. Roosevelt,K-8,Living Environment,2016,9,74,1,11.1,8,88.9,2,22.2,na,na
3,01M140,P.S. 140 Nathan Straus,K-8,Common Core Algebra,2016,3,s,s,s,s,s,s,s,na,na
4,01M140,P.S. 140 Nathan Straus,K-8,Common Core Algebra,2017,2,s,s,s,s,s,s,s,na,na

In [5]:
#There are 1,018 unique school districts in NYC

df['School DBN'].nunique()

1018

In [8]:
# the summary of measures as they're.

df.describe()

                Year   Total Tested
count  212331.000000  212331.000000
mean     2015.956069      49.364200
std         0.799726      93.023576
min      2015.000000       1.000000
25%      2015.000000       5.000000
50%      2016.000000      20.000000
75%      2017.000000      57.000000
max      2017.000000    1729.000000

In [9]:
# Realized other measures are strings.

df.dtypes

School DBN                     object
School Name                    object
School Level                   object
Regents Exam                   object
Year                            int64
Total Tested                    int64
Mean Score                     object
Number Scoring Below 65        object
Percent Scoring Below 65       object
Number Scoring 65 or Above     object
Percent Scoring 65 or Above    object
Number Scoring 80 or Above     object
Percent Scoring 80 or Above    object
Number Scoring CR              object
Percent Scoring CR             object
dtype: object

In [10]:
#Googled and found how to convert the strings into numbers.
#For example: In [143]: df[['A','B','C']] = df[['A','B','C']].apply(pd.to_numeric, errors='coerce')

df[['Mean Score','Number Scoring Below 65','Percent Scoring Below 65','Number Scoring 65 or Above','Percent Scoring 65 or Above','Number Scoring 80 or Above','Percent Scoring 80 or Above','Number Scoring CR','Percent Scoring CR']] = df[['Mean Score','Number Scoring Below 65','Percent Scoring Below 65','Number Scoring 65 or Above','Percent Scoring 65 or Above','Number Scoring 80 or Above','Percent Scoring 80 or Above','Number Scoring CR','Percent Scoring CR']].apply(pd.to_numeric, errors='coerce')

In [11]:
#Now all the measures are numeric.

df.dtypes

School DBN                      object
School Name                     object
School Level                    object
Regents Exam                    object
Year                             int64
Total Tested                     int64
Mean Score                     float64
Number Scoring Below 65        float64
Percent Scoring Below 65       float64
Number Scoring 65 or Above     float64
Percent Scoring 65 or Above    float64
Number Scoring 80 or Above     float64
Percent Scoring 80 or Above    float64
Number Scoring CR              float64
Percent Scoring CR             float64
dtype: object

In [12]:
#Now the revised descriptive stats for the new data set.
df.describe()

,Year,Total Tested,Mean Score,Number Scoring Below 65,Percent Scoring Below 65,Number Scoring 65 or Above,Percent Scoring 65 or Above,Number Scoring 80 or Above,Percent Scoring 80 or Above,Number Scoring CR,Percent Scoring CR
count,212331.000000,212331.000000,137109.000000,137109.000000,137109.000000,137109.000000,137109.000000,137109.000000,137109.000000,69651.000000,69651.000000
mean,2015.956069,49.364200,65.998967,25.140297,41.933632,46.443516,58.067855,20.506655,22.692027,29.959340,36.213730
std,0.799726,93.023576,11.288883,37.155199,28.405737,85.187123,28.405517,56.301578,26.160987,68.306798,31.092605
min,2015.000000,1.000000,15.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2015.000000,5.000000,58.300000,5.000000,17.500000,8.000000,36.000000,1.000000,2.200000,2.000000,8.800000
50%,2016.000000,20.000000,65.400000,13.000000,40.200000,21.000000,59.800000,5.000000,12.500000,9.000000,29.000000
75%,2017.000000,57.000000,73.400000,31.000000,64.000000,52.000000,82.500000,18.000000,34.500000,31.000000,58.800000
max,2017.000000,1729.000000,98.700000,697.000000,100.000000,1607.000000,100.000000,1365.000000,100.000000,1465.000000,100.000000

In [ ]:
def rescue_code(function):
    import inspect
    get_ipython().set_next_input("".join(inspect.getsourcelines(function)[0]))

In [6]:
#Trying to parse out the info. from School DBN

df['School DBN'][0][3:]

'034'

In [223]:
#I needed to create a new column called Borough by splitting the third character from School DBN. Then, I mapped the character to a more human readable name.

df['Borough'] = df['School DBN'].str[2]

borough_mapping = {
    "M": "Manhattan",
    "X": "Bronx",
    "K": "Brooklyn",
    "Q": "Queens",
    "R": "Staten Island"
}
df['Borough'] = df['Borough'].map(borough_mapping)

In [224]:
#Verified new column data

df.head(5)

,School DBN,School Name,School Level,Regents Exam,Year,Total Tested,Mean Score,Number Scoring Below 65,Percent Scoring Below 65,Number Scoring 65 or Above,Percent Scoring 65 or Above,Number Scoring 80 or Above,Percent Scoring 80 or Above,Number Scoring CR,Percent Scoring CR,Borough
0,01M034,P.S. 034 Franklin D. Roosevelt,K-8,Common Core Algebra,2017,4,s,s,s,s,s,s,s,na,na,Manhattan
1,01M034,P.S. 034 Franklin D. Roosevelt,K-8,Living Environment,2015,16,77.9,1,6.3,15,93.8,7,43.8,na,na,Manhattan
2,01M034,P.S. 034 Franklin D. Roosevelt,K-8,Living Environment,2016,9,74,1,11.1,8,88.9,2,22.2,na,na,Manhattan
3,01M140,P.S. 140 Nathan Straus,K-8,Common Core Algebra,2016,3,s,s,s,s,s,s,s,na,na,Manhattan
4,01M140,P.S. 140 Nathan Straus,K-8,Common Core Algebra,2017,2,s,s,s,s,s,s,s,na,na,Manhattan

In [18]:
#Created a new column called School Number.

df['School Number'] = df['School DBN'].str[3:]

In [19]:
#Created a new column called School District.

df['School District'] = df['School DBN'].str[:2]

In [20]:
#I wanted to understand the types of levels within 'School Level'

df['School Level'].unique()

array(['K-8', 'High school', 'Junior High-Intermediate-Middle',
       'Secondary School', 'K-12 all grades', 'Elementary'], dtype=object)

In [21]:
#I focused only on High School.

df_hs = df[df['School Level'] == 'High school']

In [22]:
#What's the higest percentage of high schools that achieve 80 or above. Found out it was 100%

df_hs['Percent Scoring 80 or Above'].max()

100.0

In [23]:
#which high school actually received 100? Which borough is it in? What about the size of the test takers? It was Queens High School for the Sciense at York College.

df_hs.sort_values(['Percent Scoring 80 or Above'], ascending=[False])

,School DBN,School Name,School Level,Regents Exam,Year,Total Tested,Mean Score,Number Scoring Below 65,Percent Scoring Below 65,Number Scoring 65 or Above,Percent Scoring 65 or Above,Number Scoring 80 or Above,Percent Scoring 80 or Above,Number Scoring CR,Percent Scoring CR,Borough,School Number,School District
199487,28Q687,Queens High School for the Sciences at York Co...,High school,Living Environment,2017,69,89.6,0.0,0.0,69.0,100.0,69.0,100.0,NaN,NaN,Queens,687,28
144649,02M418,Millennium High School,High school,Common Core English,2016,41,89.7,0.0,0.0,41.0,100.0,41.0,100.0,41.0,100.0,Manhattan,418,02
165432,10X445,Bronx High School of Science,High school,Living Environment,2015,24,93.3,0.0,0.0,24.0,100.0,24.0,100.0,NaN,NaN,Bronx,445,10
165431,10X445,Bronx High School of Science,High school,Living Environment,2015,9,93.6,0.0,0.0,9.0,100.0,9.0,100.0,NaN,NaN,Bronx,445,10
144750,02M418,Millennium High School,High school,U.S. History and Government,2015,8,92.9,0.0,0.0,8.0,100.0,8.0,100.0,NaN,NaN,Manhattan,418,02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212095,84X553,New Visions Charter High School for the Humani...,High school,U.S. History and Government,2017,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bronx,553,84
212096,84X581,South Bronx Community Charter School,High school,Common Core Algebra,2017,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bronx,581,84
212097,84X581,South Bronx Community Charter School,High school,Common Core Algebra,2017,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bronx,581,84
212098,84X581,South Bronx Community Charter School,High school,Living Environment,2017,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bronx,581,84
212100,84X581,South Bronx Community Charter School,High school,Living Environment,2017,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bronx,581,84

In [71]:
# a new data frame -nd-  is created that isolates the data for only high schools. 
nd = df[df['School Level'] == 'High school']

In [225]:
#verified

nd.head(5)

,School DBN,School Name,School Level,Regents Exam,Year,Total Tested,Mean Score,Number Scoring Below 65,Percent Scoring Below 65,Number Scoring 65 or Above,Percent Scoring 65 or Above,Number Scoring 80 or Above,Percent Scoring 80 or Above,Number Scoring CR,Percent Scoring CR,Borough,School Number,School District
18,01M292,Orchard Collegiate Academy,High school,Algebra2/Trigonometry,2015,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Manhattan,292,01
19,01M292,Orchard Collegiate Academy,High school,Algebra2/Trigonometry,2016,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Manhattan,292,01
20,01M292,Orchard Collegiate Academy,High school,Common Core Algebra,2015,12,52.3,11.0,91.7,1.0,8.3,0.0,0.0,0.0,0.0,Manhattan,292,01
21,01M292,Orchard Collegiate Academy,High school,Common Core Algebra,2016,50,63.9,25.0,50.0,25.0,50.0,3.0,6.0,15.0,30.0,Manhattan,292,01
22,01M292,Orchard Collegiate Academy,High school,Common Core Algebra,2017,53,67.5,15.0,28.3,38.0,71.7,6.0,11.3,29.0,54.7,Manhattan,292,01

In [83]:
# I wanted to sort the schools by 'Percent Scoring 80 or Above' in a descending order.

nd.sort_values('Percent Scoring 80 or Above', ascending=False)

,School DBN,School Name,School Level,Regents Exam,Year,Total Tested,Mean Score,Number Scoring Below 65,Percent Scoring Below 65,Number Scoring 65 or Above,Percent Scoring 65 or Above,Number Scoring 80 or Above,Percent Scoring 80 or Above,Number Scoring CR,Percent Scoring CR,Borough,School Number,School District
199487,28Q687,Queens High School for the Sciences at York Co...,High school,Living Environment,2017,69,89.6,0.0,0.0,69.0,100.0,69.0,100.0,NaN,NaN,Queens,687,28
144649,02M418,Millennium High School,High school,Common Core English,2016,41,89.7,0.0,0.0,41.0,100.0,41.0,100.0,41.0,100.0,Manhattan,418,02
165432,10X445,Bronx High School of Science,High school,Living Environment,2015,24,93.3,0.0,0.0,24.0,100.0,24.0,100.0,NaN,NaN,Bronx,445,10
165431,10X445,Bronx High School of Science,High school,Living Environment,2015,9,93.6,0.0,0.0,9.0,100.0,9.0,100.0,NaN,NaN,Bronx,445,10
144750,02M418,Millennium High School,High school,U.S. History and Government,2015,8,92.9,0.0,0.0,8.0,100.0,8.0,100.0,NaN,NaN,Manhattan,418,02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212095,84X553,New Visions Charter High School for the Humani...,High school,U.S. History and Government,2017,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bronx,553,84
212096,84X581,South Bronx Community Charter School,High school,Common Core Algebra,2017,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bronx,581,84
212097,84X581,South Bronx Community Charter School,High school,Common Core Algebra,2017,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bronx,581,84
212098,84X581,South Bronx Community Charter School,High school,Living Environment,2017,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bronx,581,84
212100,84X581,South Bronx Community Charter School,High school,Living Environment,2017,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bronx,581,84

In [259]:
#I wanted to aggregate by boroughs & year & understand the total number of students scoring 80 or above & the average of percent of those students.
#Plus, I wanted to understand the total number of students tested & the schools.

nd2 = nd.groupby(['Borough','Year'])\
                      .agg(total_students_scoring_80_or_above = ('Number Scoring 80 or Above', 'sum'), total_tested =('Total Tested', 'sum'), avg_percent_scoring_of_80_or_above = ('Percent Scoring 80 or Above','mean'), total_schools = ('School DBN', 'nunique') )

In [260]:
nd2

                    total_students_scoring_80_or_above  total_tested  \
Borough       Year
Bronx         2015                             95840.0        535485
              2016                             90375.0        502945
              2017                             85439.0        466330
Brooklyn      2015                            216359.0        889915
              2016                            208681.0        834990
              2017                            209146.0        782345
Manhattan     2015                            165740.0        576840
              2016                            161404.0        531510
              2017                            160816.0        494765
Queens        2015                            224206.0        847450
              2016                            219383.0        792135
              2017                            220399.0        746905
Staten Island 2015                             57099.0        212250
              2016                             52022.0        188025
              2017                             55796.0        178710

                    avg_percent_scoring_of_80_or_above  total_schools
Borough       Year
Bronx         2015                           13.268152            126
              2016                           12.978999            123
              2017                           14.257264            121
Brooklyn      2015                           16.064331            135
              2016                           15.598345            134
              2017                           16.961914            132
Manhattan     2015                           23.186276            112
              2016                           24.104842            109
              2017                           26.751502            107
Queens        2015                           23.203411             73
              2016                           23.216217             74
              2017                           25.867146             72
Staten Island 2015                           24.481145             12
              2016                           23.699267             12
              2017                           28.725626             12

In [263]:
#To simplify, I wanted to combine the three years.

nd3 = nd.groupby(['Borough'])\
                      .agg(total_students_scoring_80_or_above = ('Number Scoring 80 or Above', 'sum'), total_tested =('Total Tested', 'sum'), avg_percent_scoring_of_80_or_above = ('Percent Scoring 80 or Above','mean'), total_schools = ('School DBN', 'nunique') )

In [265]:
nd4 = nd3.sort_values('avg_percent_scoring_of_80_or_above', ascending=False)

In [266]:
#Verified it
nd4

,total_students_scoring_80_or_above,total_tested,avg_percent_scoring_of_80_or_above,total_schools
Borough,,,,
Staten Island,164917.0,578985,25.478720,12
Manhattan,487960.0,1603115,24.571897,112
Queens,663988.0,2386490,24.019677,74
Brooklyn,634186.0,2507250,16.168293,135
Bronx,271654.0,1504760,13.456026,130

In [249]:
#I needed to compare the Queens High School for the Sciense at York College against the borough average.

nd.loc[df['School DBN'] == '28Q687'].groupby(['School Name'])\
                      .agg(total_students_scoring_80_or_above = ('Number Scoring 80 or Above', 'sum'), total_tested =('Total Tested', 'sum'), avg_percent_scoring_of_80_or_above = ('Percent Scoring 80 or Above','mean') )

,total_students_scoring_80_or_above,total_tested,avg_percent_scoring_of_80_or_above
School Name,,,
Queens High School for the Sciences at York Colleg,11475.0,13830,86.420982

Queens High School for the Sciences at York College has one of the smartest student bodies in NYC public high schools. In fact, 86% of the students score 80 or above from 2015 to 2017, beating all other high schools. As a point of comparison, in Staten Island, the average percentage for those scoring 80 or higher was only 25%, the highest for all five boroughs. Bronx had 13%, the lowest.

As for visualization, I wanted to create a scatter plot that shows the relationship between the total number of students who took the test and the avg. percentage of those who scored 80% and above. The size of the bubble was each school's size of the students who scored 80% and above.

In [267]:
nd5 = nd.groupby(['School Name','Borough'])\
                      .agg(total_students_scoring_80_or_above = ('Number Scoring 80 or Above', 'sum'), total_tested =('Total Tested', 'sum'), avg_percent_scoring_of_80_or_above = ('Percent Scoring 80 or Above','mean') )

In [268]:
nd5.head(10)

,,total_students_scoring_80_or_above,total_tested,avg_percent_scoring_of_80_or_above
School Name,Borough,,,
47 The American Sign Language and English Secondar,Manhattan,678.0,6700,9.564734
A. Philip Randolph Campus High School,Manhattan,8287.0,37735,19.628065
ACORN Community High School,Brooklyn,1036.0,10985,8.189848
Abraham Lincoln High School,Brooklyn,9869.0,70290,13.339558
Abraham Lincoln Yabc,Brooklyn,194.0,3335,6.887179
Academy for Careers in Television and Film,Queens,6707.0,19270,31.798516
Academy for Conservation and the Environment,Brooklyn,1227.0,11690,9.351626
Academy for Environmental Leadership,Brooklyn,768.0,11830,6.300830
Academy for Health Careers,Brooklyn,1477.0,10000,13.898780
Academy for Language and Technology,Bronx,1263.0,13310,12.311656

In [269]:
# Needed to understand what was the index after aggregation
# Used these two functions to get more info: print(list(nd3.index.values)) and print(list(nd3.index.values.tolist()))
# Then reset the index for the new data frame

nd6 = nd5.reset_index()

In [270]:
#Verified it

nd6.columns

Index(['School Name', 'Borough', 'total_students_scoring_80_or_above',
       'total_tested', 'avg_percent_scoring_of_80_or_above'],
      dtype='object')

In [271]:
#I googled and found a librar for plotly. So I used "import plotly.express as px" to generate the following chart.

fig = px.scatter(nd6, y='avg_percent_scoring_of_80_or_above', size= 'total_students_scoring_80_or_above', x = 'total_tested', color = 'Borough', hover_name = 'School Name', size_max=60)

fig.show()